### ISSUE TITLE
Not working on XBMC Gotham and KODI Helix

### ISSUE THREAD

**Issue by mrrneo** [marinewater/plugin.video.mlg.tv#1]
Hi,
I can not install the addon on XBMC 13.2 and Kodi 14.2. I got this error message "Dependencies not met".

**Comment by marinewater** [comment]
Yeah, it's currently Isengard only, because I only tested in on Kodi 15.

You can try to change the xbmc.python version in addon.xml (_line 4_) from **2.20.0** to **2.14.0**.

Tell me if it works properly and I'll try to get it switched to the Gotham 13.x branch.

**Comment by mrrneo** [comment]
It works flawlessly on both.

Thanks for your attention. :)
